#!/bin/bash
#
# [AI GENERATED - GOVERNANCE PROTOCOL]
# ──────────────────────────────────────────────────────────────
# Model:       Claude Opus 4.6
# Tier:        L2
# Logic:       Post-run cost check for GitHub Actions.
# Root Cause:  Sprint task T190 — GitHub Actions cost gate.
# Context:     Calculates and reports AI costs for the workflow run.
# Suitability: L2 — Standard shell scripting.
# ──────────────────────────────────────────────────────────────

set -e

# Configuration from environment
ALFRED_API_KEY="${ALFRED_API_KEY:-}"
ALFRED_API_URL="${ALFRED_API_URL:-https://api.alfred.ai}"
BUDGET_LIMIT="${ALFRED_BUDGET_LIMIT:-5.00}"
FAIL_ON_EXCEEDED="${ALFRED_FAIL_ON_EXCEEDED:-true}"
START_BALANCE="${ALFRED_START_BALANCE:-0}"
REPORT_USAGE="${REPORT_USAGE:-true}"

echo "📊 Alfred Cost Gate - Post-Run Check"
echo "======================================"

# Get current balance
RESPONSE=$(curl -s \
  -H "Authorization: Bearer $ALFRED_API_KEY" \
  -H "Content-Type: application/json" \
  "$ALFRED_API_URL/v1/wallets/me")

END_BALANCE=$(echo "$RESPONSE" | jq -r '.balance // 0')

# Calculate cost
RUN_COST=$(echo "$START_BALANCE - $END_BALANCE" | bc -l)
# Handle negative (refunds or credits during run)
if (( $(echo "$RUN_COST < 0" | bc -l) )); then
  RUN_COST="0"
fi

BUDGET_REMAINING=$(echo "$BUDGET_LIMIT - $RUN_COST" | bc -l)

echo "💰 Run Statistics:"
echo "  Start Balance: \$$START_BALANCE"
echo "  End Balance:   \$$END_BALANCE"
echo "  Run Cost:      \$$RUN_COST"
echo "  Budget Limit:  \$$BUDGET_LIMIT"
echo "  Budget Used:   $(echo "scale=1; $RUN_COST / $BUDGET_LIMIT * 100" | bc)%"

# Set outputs
echo "run-cost=$RUN_COST" >> $GITHUB_OUTPUT
echo "budget-remaining=$BUDGET_REMAINING" >> $GITHUB_OUTPUT
echo "balance=$END_BALANCE" >> $GITHUB_OUTPUT

# Check if budget exceeded
if (( $(echo "$RUN_COST > $BUDGET_LIMIT" | bc -l) )); then
  echo "⚠️ Budget exceeded: \$$RUN_COST > \$$BUDGET_LIMIT"
  echo "status=failed" >> $GITHUB_OUTPUT
  
  if [ "$FAIL_ON_EXCEEDED" = "true" ]; then
    echo "❌ Failing workflow due to budget exceeded"
    exit 1
  else
    echo "⚠️ Continuing despite budget exceeded (fail-on-exceeded=false)"
  fi
elif (( $(echo "$RUN_COST > $BUDGET_LIMIT * 0.8" | bc -l) )); then
  echo "⚠️ Warning: Used 80%+ of budget"
  echo "status=warning" >> $GITHUB_OUTPUT
else
  echo "✅ Budget check passed"
  echo "status=passed" >> $GITHUB_OUTPUT
fi

# Generate PR comment if in PR context
if [ -n "$GITHUB_EVENT_PATH" ] && [ "$REPORT_USAGE" = "true" ]; then
  PR_NUMBER=$(jq -r '.pull_request.number // empty' "$GITHUB_EVENT_PATH" 2>/dev/null || true)
  
  if [ -n "$PR_NUMBER" ]; then
    echo "📝 Posting usage report to PR #$PR_NUMBER..."
    
    COMMENT_BODY="## 🤖 Alfred AI Cost Report

| Metric | Value |
|--------|-------|
| Run Cost | \\\$$RUN_COST |
| Budget Limit | \\\$$BUDGET_LIMIT |
| Budget Remaining | \\\$$BUDGET_REMAINING |
| Wallet Balance | \\\$$END_BALANCE |

---
_Generated by [Alfred Cost Gate](https://alfred.ai)_"
    
    curl -s -X POST \
      -H "Authorization: token $GITHUB_TOKEN" \
      -H "Content-Type: application/json" \
      -d "{\"body\": \"$COMMENT_BODY\"}" \
      "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" > /dev/null 2>&1 || true
    
    echo "✅ Usage report posted"
  fi
fi

echo ""
echo "✅ Alfred Cost Gate check complete"
