"""
# [AI GENERATED]
# Model: GitHub Copilot (GPT-5 mini)
# Logic: Generate a `tests/fixtures/credentials.py` file from environment variables.
# Why: Provide a single, CI-friendly way to supply test credentials without committing secrets.
# Root Cause: Tests relied on scattered hardcoded credentials and missing CI wiring.
# Context: CI pipelines should provide the required secrets as environment variables (see the workflow example).
# Model Suitability: This is a simple utility script; maintainers should verify the env var names match CI secrets.
"""

from pathlib import Path
import os
import json
import sys

DEFAULT_KEYS = [
    "TEST_ADMIN_PASSWORD",
    "TEST_PASSWORD",
    "TEST_API_KEY",
    "ADMIN_PASSWORD",
    "API_KEY",
]


def main():
    out_dir = Path("tests/fixtures")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "credentials.py"

    keys = os.getenv("TEST_CREDENTIAL_KEYS")
    if keys:
        keys = [k.strip() for k in keys.split(",") if k.strip()]
    else:
        keys = DEFAULT_KEYS

    creds = {}
    for k in keys:
        v = os.getenv(k)
        if v:
            creds[k] = v

    if not creds:
        print(
            "Warning: no credentials found in environment. No file will be created.",
            file=sys.stderr,
        )
        # ensure no leftover file exists
        if out_file.exists():
            out_file.unlink()
        sys.exit(0)

    # Write a simple python file with a CREDENTIALS dict
    with out_file.open("w", encoding="utf-8") as f:
        f.write(
            "# Auto-generated by dev/ci/generate_test_credentials.py - DO NOT COMMIT this file\n"
        )
        f.write("# Provide secrets via CI or local env vars.\n")
        f.write("CREDENTIALS = ")
        json.dump(creds, f, indent=4)
        f.write("\n")

    print(f"Wrote credentials to {out_file}")


if __name__ == "__main__":
    main()
