"""Generate `tests/fixtures/credentials.py` from environment variables.

Usage: CI pipelines should set required secrets as environment variables and
invoke this script before running tests. The generated file should NOT be
committed to source control.
"""

import json
import logging
import os
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_KEYS = [
    "TEST_ADMIN_PASSWORD",
    "TEST_PASSWORD",
    "TEST_API_KEY",
    "ADMIN_PASSWORD",
    "API_KEY",
]


def main() -> None:
    out_dir = Path("tests/fixtures")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "credentials.py"

    keys_env = os.getenv("TEST_CREDENTIAL_KEYS")
    if keys_env:
        keys = [k.strip() for k in keys_env.split(",") if k.strip()]
    else:
        keys = DEFAULT_KEYS

    creds = {k: os.getenv(k) for k in keys if os.getenv(k)}

    if not creds:
        logger.warning("No credentials found in environment. No file will be created.")
        if out_file.exists():
            out_file.unlink()
        sys.exit(0)

    with out_file.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by dev/ci/generate_test_credentials.py - DO NOT COMMIT this file\n")
        f.write("# Provide secrets via CI or local env vars.\n")
        f.write("CREDENTIALS = ")
        json.dump(creds, f, indent=4)
        f.write("\n")

    logger.info("Wrote credentials to %s", out_file)


if __name__ == "__main__":
    main()
